### ISSUE TITLE
Amazon UK version?

### ISSUE THREAD

**Issue by figjamalba** [dcwangmit01/amazon-invoice-downloader#4]
Would it be possible to adapt this for Amazon UK.
I have tried, modifying line 80 and 158 to amazon.co.uk
And fix the output on line 142, to replace £ instead of $ and zapping the comma in the format.

The next change would be 141 to read "%d %B %Y"

So far so good except it failed on 160 
AttributeError: 'NoneType' object has no attribute 'get_attribute'. Did you mean: '__getattribute__'?

And since I am a n00b, I have no idea to fix this.

**Comment by figjamalba** [comment]
Here is the error output

```
Saving file [/home/gary/amazon-invoice-downloader/dist/amazon_invoice_downloader-0.4.0/downloads/20240220_9.99_amazon_204-9792541-9419510.pdf]
Traceback (most recent call last):
  File "/home/gary/.local/share/hatch/env/virtual/amazon-invoice-downloader/OUBFGZow/amazon-invoice-downloader/bin/amazon-invoice-downloader", line 8, in <module>
    sys.exit(amazon_invoice_downloader())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gary/amazon-invoice-downloader/dist/amazon_invoice_downloader-0.4.0/src/amazon_invoice_downloader/cli/__init__.py", line 179, in amazon_invoice_downloader
    run(playwright, args)
  File "/home/gary/amazon-invoice-downloader/dist/amazon_invoice_downloader-0.4.0/src/amazon_invoice_downloader/cli/__init__.py", line 160, in run
    ).get_attribute("href")
      ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_attribute'. Did you mean: '__getattribute__'?

```

**Comment by jbredcar** [comment]
I would love to use this for Amazon UK too please!

**Comment by cypris75** [comment]
I created a simplified Jupyter Notebook based on the code of this repo.

See gist here:

https://gist.github.com/cypris75/dc8baf5ea67b87d87ae839468ffdaa0c

To make it work for UK you would need to adjust the following:

- Locale
- Label "Hallo, anmelden"
- Labels for login fields and buttons
- Label for your orders
- All amazon.de references
- ...

Hope this helps someone.

**Comment by luke-burnett** [comment]
Created a UK fork to be run as a python script: https://github.com/luke-burnett/amazon-invoice-downloader/tree/main

Thanks to Cypris75 too as some of their code is used.

**Comment by pboushy** [comment]
@dcwangmit01 @luke-burnett - I've been investigating some bugs with this and enhancing various areas in general that I'm wanting to push upstream.
I'm also up to making this work on more languages.
Are y'all interested in collaborating to make this work on more Amazon sites?

It looks like https://github.com/cr7pt0gr4ph7/amazon-invoice-downloader already has a good bit of improvements to enable amazon.de, including removing quite a bit of language specific items.

I've emailed the owner to see if they're interested in collaborating as well since it won't let me mention them here.

**Comment by dcwangmit01** [comment]
@figjamalba @pboushy @luke-burnett @cypris75 .  I just updated this project to make it work with the current US amazon.com site as of August 2025.  I'm open to accepting any PR's to make it work internationally, and even making any of you contributors so you can merge.

BTW, the AI Assistant MCP support makes development and debugging of this project a lot easier.  All hail AI.

**Comment by pboushy** [comment]
I couldn't figure out how to use the AI Assistant MCP so I just submitted #11 to help make it easier for people to determine what needs to change when `click()` errors in different spots.

I did look at internationalizing this, but I've not done any kind of internationalization and python's `i18n` looks rather messy. I'm gonna do some more research, but if anyone has an idea of how to internationalize this more, I'd be game to collaborate on it.

**Comment by mmcgn** [comment]
Hi everybody,
I have just been trying to get the German version running, with AI assistance, as I am not a python programmer.
As for the many redirections of amazon ist seems to be a bit tricky.
Additionally the layout has changed a bit.
So I was wondering whether there is any upgrade regarding a multi-national version that supports different countries as indicated above...
